---
- name: Deploy Nodejs runtime and App
  hosts: all
  tasks:
  - name: install nodejs
    dnf:
      name: '@nodejs/development'
      state: present
  - name: install nodejs systemd unit file
    file: 
      src: 
      dst: 
  - name: install apache proxy definition
    copy:
      src: nodeproxy.conf
      dest: /etc/httpd/conf.d/nodeproxy.conf
  - name: copy index.jsp to webapp directory
    copy:
      src: index.jsp
      dest: /var/lib/tomcat/webapps/coolapp/
